apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: container-1
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: container-2
      image: busybox:latest
      command: ["/bin/sh", "-c", "echo 'Hello from container 2' > /data/index.html; sleep 3600"]